config:
  target: "{{ $env.OPENWEATHER_BASE_URL }}" 
  defaults:
    headers:
      Content-Type: "application/json"
  variables:
    API_KEY: "{{ $env.OPENWEATHER_BASE_URL }}"

scenarios:
  - name: "Weather API Load Test"
    flow:
      - get:
          url: "/weather"
          qs:
            q: "London"
            appid: "{{ API_KEY }}"
